# Generated by Django 4.2.9 on 2024-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('age', models.SmallIntegerField()),
                ('gen', models.CharField(max_length=1)),
                ('classid', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'stu',
            },
        ),
    ]
